from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

from .flake import locked_ref, read_lock, root_inputs, short_ref
from .forge import ForgeError, Forgejo
from .git import commit_all, push_force, run, worktree


def env_first(*names: str) -> str:
    for name in names:
        value = os.environ.get(name)
        if value:
            return value
    return ""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="update flake inputs and create Forgejo pull requests")
    parser.add_argument("--forgejo-url", default=env_first("FORGEJO_URL", "GITEA_URL"))
    parser.add_argument("--forgejo-repository", default=env_first("FORGEJO_REPOSITORY", "GITEA_REPOSITORY"))
    parser.add_argument("--forgejo-token", default=env_first("FORGEJO_TOKEN", "GITEA_TOKEN"))
    parser.add_argument("--base-branch", default="main")
    parser.add_argument("--branch-prefix", default="update-")
    parser.add_argument("--auto-merge", action="store_true")
    parser.add_argument("--cleanup-stale-branches", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--git-author-name", default=env_first("GIT_AUTHOR_NAME") or "nixfiles-bot")
    parser.add_argument("--git-author-email", default=env_first("GIT_AUTHOR_EMAIL") or "nixfiles-bot@noreply.codeberg.org")
    parser.add_argument("--git-committer-name", default=env_first("GIT_COMMITTER_NAME") or "nixfiles-bot")
    parser.add_argument("--git-committer-email", default=env_first("GIT_COMMITTER_EMAIL") or "nixfiles-bot@noreply.codeberg.org")
    return parser.parse_args()


def validate_args(args: argparse.Namespace) -> None:
    missing = []
    if not args.dry_run and not args.forgejo_url:
        missing.append("--forgejo-url or FORGEJO_URL/GITEA_URL")
    if not args.dry_run and not args.forgejo_repository:
        missing.append("--forgejo-repository or FORGEJO_REPOSITORY/GITEA_REPOSITORY")
    if not args.dry_run and not args.forgejo_token:
        missing.append("--forgejo-token or FORGEJO_TOKEN/GITEA_TOKEN")
    if missing:
        raise SystemExit("missing: " + ", ".join(missing))


def update_input(input_name: str, args: argparse.Namespace, forge: Forgejo | None) -> bool:
    lock_before = read_lock(Path("flake.lock"))
    old = locked_ref(lock_before, input_name)
    branch = f"{args.branch_prefix}{input_name}".replace("/", "-").strip("-")

    print(f"update {input_name}: branch {branch}")
    with worktree(branch, args.base_branch) as path:
        run(["nix", "flake", "lock", "--update-input", input_name], cwd=path)
        lock_after = read_lock(path / "flake.lock")
        new = locked_ref(lock_after, input_name)
        title = f"{input_name}: update to {short_ref(new)}"
        commit_message = f"update {input_name}"
        body = (
            f"updates flake input `{input_name}`.\n\n"
            f"- old: `{old}`\n"
            f"- new: `{new}`\n\n"
            "generated by `scripts.update_flake_inputs`."
        )

        if not commit_all(
            path,
            commit_message,
            args.git_author_name,
            args.git_author_email,
            args.git_committer_name,
            args.git_committer_email,
        ):
            print(f"update {input_name}: no changes")
            return True

        if args.dry_run:
            print(f"update {input_name}: would push {branch} and create PR {title!r}")
            return True

        push_force(path, branch)
        assert forge is not None
        existing = forge.find_open_pr(branch, args.base_branch)
        try:
            if existing is None:
                pr = forge.create_pull_request(branch, args.base_branch, title, body)
                print(f"update {input_name}: created PR #{pr.number}: {pr.html_url}")
            else:
                pr = existing
                print(f"update {input_name}: reuse PR #{pr.number}: {pr.html_url}")
        except ForgeError as error:
            if error.status == 429:
                print(f"update {input_name}: PR creation rate-limited; branch kept: {branch}")
                return True
            raise

        if args.auto_merge:
            forge.merge_pull_request(pr.number)
            print(f"update {input_name}: merge requested for PR #{pr.number}")
        return True


def cleanup_stale_branches(forge: Forgejo, prefix: str) -> None:
    open_heads = forge.list_open_pr_heads()
    for branch in forge.list_branches():
        if not branch.startswith(prefix):
            continue
        if branch in open_heads:
            print(f"keep   {branch} (open PR)")
            continue
        print(f"delete {branch} (stale, no open PR)")
        try:
            forge.delete_branch(branch)
        except ForgeError as error:
            if error.status != 404:
                raise


def main() -> int:
    args = parse_args()
    validate_args(args)

    lock = read_lock(Path("flake.lock"))
    inputs = root_inputs(lock)
    print("inputs: " + ", ".join(inputs))

    if args.dry_run:
        return 0

    forge = Forgejo(args.forgejo_url, args.forgejo_repository, args.forgejo_token)
    forge.check_auth()

    if args.cleanup_stale_branches:
        cleanup_stale_branches(forge, args.branch_prefix)

    failed: list[str] = []
    for input_name in inputs:
        try:
            update_input(input_name, args, forge)
        except (ForgeError, subprocess.CalledProcessError, OSError) as error:
            print(f"update {input_name}: failed: {error}", file=sys.stderr)
            failed.append(input_name)

    if failed:
        print("failed inputs: " + ", ".join(failed), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
