name: renovate
on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:
concurrency:
  group: renovate
  cancel-in-progress: false
jobs:
  renovate:
    runs-on: codeberg-small
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: install nix
        uses: https://github.com/NixOS/nix-installer-action@6b8548fe06acfb0155a50ab5d561accb215764cc # main
        with:
          extra-conf: |
            experimental-features = nix-command flakes
      - name: renovate
        env:
          RENOVATE_PLATFORM: forgejo
          RENOVATE_ENDPOINT: ${{ forgejo.server_url }}
          RENOVATE_REPOSITORIES: ${{ forgejo.repository }}
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_GITHUB_COM_TOKEN: ${{ secrets.RENOVATE_GITHUB_COM_TOKEN }}
          LOG_LEVEL: info
        run: nix run nixpkgs#renovate
