name: update flake inputs
on:
  schedule:
    - cron: "0 3 * * *" # nightly at 03:00 UTC
  workflow_dispatch:
jobs:
  update:
    runs-on: codeberg-small
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: install nix
        uses: https://github.com/NixOS/nix-installer-action@6b8548fe06acfb0155a50ab5d561accb215764cc # main
        with:
          extra-conf: |
            experimental-features = nix-command flakes
      - name: update flake inputs
        env:
          GITEA_TOKEN: ${{ secrets.TOKEN }}
          NIX_CONFIG: |
            access-tokens = github.com=${{ secrets.RENOVATE_GITHUB_COM_TOKEN }}
        run: |
          nix run \
            "github:Mic92/update-flake-inputs-gitea" -- \
            --gitea-url "${{ forgejo.server_url }}" \
            --gitea-repository "${{ forgejo.repository }}" \
            --base-branch "main" \
            --git-author-name "nixfiles-bot" \
            --git-author-email "nixfiles-bot@noreply.codeberg.org" \
            --git-committer-name "nixfiles-bot" \
            --git-committer-email "nixfiles-bot@noreply.codeberg.org" \
            --auto-merge
