name: update flake inputs
on:
  schedule:
    - cron: "0 3 * * *" # nightly at 03:00 UTC
  workflow_dispatch:
jobs:
  update:
    runs-on: codeberg-tiny
    steps:
      - uses: actions/checkout@v4
      - name: update flake inputs
        uses: https://github.com/Mic92/update-flake-inputs-gitea@main
        with:
          gitea-url: https://codeberg.org
          gitea-token: ${{ secrets.TOKEN }}
          gitea-repository: fosskar/nixfiles
          auto-merge: true
