name: validate
on:
  push:
    branches:
      - main
jobs:
  formatting-check:
    runs-on: codeberg-small
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: install nix
        uses: https://github.com/cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
      - name: check formatting with treefmt
        run: |
          nix fmt -- --fail-on-change
  linting:
    runs-on: codeberg-small
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: install nix
        uses: https://github.com/cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
      - name: check for unused nix code with deadnix
        run: |
          nix run nixpkgs#deadnix -- --fail .
