{ config, ... }:
{
  flake.clan.inventory.instances = {
    monitoring = {
      module = {
        name = "monitoring";
        input = "self";
      };

      roles = {
        server.machines."nixbox".settings = {
          extraTelegrafTargets = [ "openwrt.lan:9273" ];
          # public certs come from traefik and netbird-proxy on gateway, one per
          # host; the local wildcard is checked by gatus in caddy.nix
          certificateSources = map (host: "https://${host}.${config.flake.domains.public}:443") [
            "auth"
            "buzz"
            "maps"
            "matrix"
            "nb"
            "nixbot"
            "radicle"
          ];
        };
        client.tags = [ "server" ];
      };
    };

    beszel = {
      module = {
        name = "beszel";
        input = "self";
      };
      roles = {
        # icmp between clan machines on every clan network is generated by the
        # module; these are the service and external probes on top
        server.machines."nixbox".settings.monitors = [
          # gateway offloads builds to nix-grpc-store over yggdrasil
          {
            system = "gateway";
            target = "nixworker.s";
            protocol = "tcp";
            port = 50051;
          }
          # garage rpc between the two nodes; replicated writes wait on it
          {
            system = "nixbox";
            target = "nixworker.s";
            protocol = "tcp";
            port = 3901;
          }
          # round trip through netbird-proxy on gateway
          {
            system = "nixbox";
            target = "https://niks3.${config.flake.domains.public}/nix-cache-info";
            protocol = "http";
          }
          # the router agent resolves through adguard home on 127.0.0.1:53 and
          # unbound behind it; clan machines go through systemd-resolved, whose
          # cache and fallback servers would hide an adguard outage
          {
            system = "openwrt";
            target = "cache.nixos.org";
            protocol = "dns";
          }
        ];
        server.machines."nixbox".settings.extraSystems = [
          {
            name = "home-assistant";
            host = "192.168.10.50";
          }
          {
            name = "openwrt";
            host = config.flake.router.srv;
          }
          {
            name = "openwrt-ap";
            host = "192.168.10.2";
          }
        ];
        client.tags = [ "server" ];
        client.machines."nixbox".settings = {
          sensors = "-nct6798_cputin,-nct6798_auxtin0,-nct6798_auxtin2,-nct6798_auxtin4,-bnxt_en";
          filesystem = "/persist";
          # zfs pools and datasets are reported automatically (beszel storage pools);
          # only the vfat esps need listing
          extraFilesystems = "/boot__Boot,/boot-fallback__BootFallback";
          smartDevices = "/dev/nvme0,/dev/nvme1,/dev/sda,/dev/sdb,/dev/sdc,/dev/sdd,/dev/sde,/dev/sdf,/dev/sdg";
        };
      };
    };

    ups = {
      module = {
        name = "ups";
        input = "self";
      };
      roles = {
        primary.machines."nixbox" = { };
        secondary.machines."nixworker" = { };
        secondary.machines."desktop" = { };
      };
    };
  };
}
