{ config, ... }:
{
  flake.clan.inventory.instances = {
    monitoring = {
      module = {
        name = "monitoring";
        input = "self";
      };

      roles = {
        server.machines."nixbox".settings = {
          extraTelegrafTargets = [ "openwrt.lan:9273" ];
          # public certs come from traefik and netbird-proxy on gateway, one per
          # host; the local wildcard is checked by gatus in caddy.nix
          certificateSources = map (host: "https://${host}.${config.flake.domains.public}:443") [
            "auth"
            "buzz"
            "maps"
            "matrix"
            "nb"
            "nixbot"
            "radicle"
          ];
        };
        client.tags = [ "server" ];
      };
    };

    beszel = {
      module = {
        name = "beszel";
        input = "self";
      };
      roles = {
        # icmp between clan machines on every clan network is generated by the
        # module; these are the service and external probes on top
        server.machines."nixbox".settings.monitors = [
          # gateway offloads builds to nix-grpc-store over yggdrasil
          {
            system = "gateway";
            target = "nixworker.s";
            protocol = "tcp";
            port = 50051;
          }
          # garage rpc between the two nodes; replicated writes wait on it
          {
            system = "nixbox";
            target = "nixworker.s";
            protocol = "tcp";
            port = 3901;
          }
          # round trip through netbird-proxy on gateway
          {
            system = "nixbox";
            target = "https://niks3.${config.flake.domains.public}/nix-cache-info";
            protocol = "http";
          }
          # home uplink; compare with the generated nixbox -> gateway internet probe
          {
            system = "nixbox";
            target = "1.1.1.1";
            protocol = "icmp";
          }
        ];
        server.machines."nixbox".settings.extraSystems = [
          {
            name = "home-assistant";
            host = "192.168.10.50";
          }
          {
            name = "openwrt";
            host = "192.168.20.1";
          }
          {
            name = "openwrt-ap";
            host = "192.168.10.2";
          }
        ];
        client.tags = [ "server" ];
        client.machines."nixbox".settings = {
          sensors = "-nct6798_cputin,-nct6798_auxtin0,-nct6798_auxtin2,-nct6798_auxtin4,-bnxt_en";
          filesystem = "/persist";
          extraFilesystems = "/__Root,/nix__Nix,/boot__Boot,/boot-fallback__BootFallback,/tank__Tank,/tank/apps__Apps,/tank/media__Media,/tank/shares__Shares,/tank/backup__Backup";
          smartDevices = "/dev/nvme0,/dev/nvme1,/dev/sda,/dev/sdb,/dev/sdc,/dev/sdd,/dev/sde,/dev/sdf,/dev/sdg";
        };
      };
    };

    ups = {
      module = {
        name = "ups";
        input = "self";
      };
      roles = {
        primary.machines."nixbox" = { };
        secondary.machines."nixworker" = { };
        secondary.machines."desktop" = { };
      };
    };
  };
}
