# Expression generated by update.sh; do not edit it by hand!
{ callPackage, ... }@args:

let
  pname = "brave-origin";
  version = "1.94.98";

  allArchives = {
    x86_64-linux = {
      url = "https://github.com/brave/brave-browser/releases/download/v${version}/brave-origin-beta_${version}_amd64.deb";
      hash = "sha256-ur8Z4ND1U/3/BTcPjxH5j6Q235dLQ98yg64pjdFSpMw=";
    };
  };

in
callPackage ./make-brave.nix (removeAttrs args [ "callPackage" ]) {
  inherit pname version;
  archives = allArchives;
}
