# Expression generated by update.sh; do not edit it by hand!
{ callPackage, ... }@args:

let
  pname = "brave-origin";
  version = "1.93.107";

  allArchives = {
    x86_64-linux = {
      url = "https://github.com/brave/brave-browser/releases/download/v${version}/brave-origin-beta_${version}_amd64.deb";
      hash = "sha256-YCpS8cCbN2z+JvbPS6Y6jj8fTrC136kvjyKpvUwFrz8=";
    };
  };

in
callPackage ./make-brave.nix (removeAttrs args [ "callPackage" ]) {
  inherit pname version;
  archives = allArchives;
}
