# Expression generated by update.sh; do not edit it by hand!
{ callPackage, ... }@args:

let
  pname = "brave-origin";
  version = "1.92.126";

  allArchives = {
    x86_64-linux = {
      url = "https://github.com/brave/brave-browser/releases/download/v${version}/brave-origin-beta_${version}_amd64.deb";
      hash = "sha256-NqHY4DX1ZiZJAnAhA28npn9B31+As5wYehoRH2gVDf0=";
    };
  };

in
callPackage ./make-brave.nix (removeAttrs args [ "callPackage" ]) {
  inherit pname version;
  archives = allArchives;
}
