#!/usr/bin/env nix
#!nix shell nixpkgs#bash nixpkgs#curl nixpkgs#gnused nixpkgs#nix nixpkgs#jq -c bash
# shellcheck shell=bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

# prefer RENOVATE_GITHUB_COM_TOKEN (set in ci) > GITHUB_TOKEN (only useful if it's actually a github pat)
gh_token="${RENOVATE_GITHUB_COM_TOKEN:-${GITHUB_TOKEN:-}}"

releasesJson="$(curl --fail -s ${gh_token:+-u ":$gh_token"} "https://api.github.com/repos/brave/brave-browser/releases?per_page=100")"

releaseJson="$(
  jq -c '
    map(
      select(.name | test("Beta"; "i"))
      | .tag_name as $tag
      | ($tag | ltrimstr("v")) as $version
      | .assets as $assets
      | select(
          all([
            "brave-origin-beta_\($version)_amd64.deb"
          ][]; . as $name | any($assets[]?.name; . == $name))
        )
    )
    | first
  ' <<<"$releasesJson"
)"

latestVersion="$(jq -r '.tag_name | ltrimstr("v")' <<<"$releaseJson")"

if [[ -z $latestVersion || $latestVersion == "null" ]]; then
  echo "Could not determine latest brave-origin version." >&2
  exit 1
fi

hasAsset() {
  jq -e --arg name "$1" 'any(.assets[]?.name; . == $name)' <<<"$releaseJson" >/dev/null
}

requireAsset() {
  if ! hasAsset "$1"; then
    echo "Missing expected asset: $1" >&2
    exit 1
  fi
}

requireAsset "brave-origin-beta_${latestVersion}_amd64.deb"

if hasAsset "brave-origin-beta_${latestVersion}_arm64.deb"; then
  hashAarch64="$(nix-hash --to-sri --type sha256 "$(nix-prefetch-url --type sha256 "https://github.com/brave/brave-browser/releases/download/v${latestVersion}/brave-origin-beta_${latestVersion}_arm64.deb")")"
fi

hashAmd64="$(nix-hash --to-sri --type sha256 "$(nix-prefetch-url --type sha256 "https://github.com/brave/brave-browser/releases/download/v${latestVersion}/brave-origin-beta_${latestVersion}_amd64.deb")")"

cat >"$SCRIPT_DIR/package.nix" <<EOF
# Expression generated by update.sh; do not edit it by hand!
{ stdenv, callPackage, ... }@args:

let
  pname = "brave-origin";
  version = "${latestVersion}";

  allArchives = {
EOF

if hasAsset "brave-origin-beta_${latestVersion}_arm64.deb"; then
  cat >>"$SCRIPT_DIR/package.nix" <<EOF
    aarch64-linux = {
      url = "https://github.com/brave/brave-browser/releases/download/v\${version}/brave-origin-beta_\${version}_arm64.deb";
      hash = "${hashAarch64}";
    };
EOF
fi

cat >>"$SCRIPT_DIR/package.nix" <<EOF
    x86_64-linux = {
      url = "https://github.com/brave/brave-browser/releases/download/v\${version}/brave-origin-beta_\${version}_amd64.deb";
      hash = "${hashAmd64}";
    };
  };

in
callPackage ./make-brave.nix (removeAttrs args [ "callPackage" ]) {
  inherit pname version;
  archives = allArchives;
}
EOF
