##############################################################################
# User custom options added in the server: clause part of UCI 'unbound.conf'
#
# Add your own option statements here when they are not covered by UCI. This
# file is placed _inside_ the server: clause with an include: statement. Do
# not start other clauses here, because that would break the server: clause.
# Use 'unbound_ext.conf' to start new clauses at the end of 'unbound.conf'.
##############################################################################

# this is for keeping rebind protection but allow domains to resolve to local ips
private-domain: "nx3.eu"

statistics-cumulative: yes

# see: https://unbound.docs.nlnetlabs.nl/en/latest/topics/core/serve-stale.html
# prefetch: already enabled by UCI recursion=aggressive
serve-expired: yes
serve-expired-ttl: 86400
serve-expired-client-timeout: 0

## OPT

# cache size (override UCI resource=large defaults which are too small for 1GB RAM)
msg-cache-size: 32m
rrset-cache-size: 64m

# more outgoing connections
# with libevent
outgoing-range: 8192
num-queries-per-thread: 4096

# improve udp performance on linux
so-reuseport: yes
